# Generated by Django 3.0.5 on 2020-10-13 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplesocial2', '0002_siteposts_userpostcomments_userposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitePosts',
            new_name='SitePost',
        ),
        migrations.RenameModel(
            old_name='UserPosts',
            new_name='UserPost',
        ),
        migrations.RenameModel(
            old_name='UserPostComments',
            new_name='UserPostComment',
        ),
    ]
