# Generated by Django 3.0.5 on 2020-10-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0004_auto_20201013_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postpic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
