# Generated by Django 3.0.5 on 2020-10-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0007_auto_20201013_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepost',
            name='postpic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='commentpic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
