# Generated by Django 3.0.5 on 2020-10-13 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplesocial2', '0016_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postlike',
            field=models.ManyToManyField(blank=True, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendRquest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_answer', models.BooleanField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('answer_date', models.DateTimeField()),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_by', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
