# Generated by Django 3.0.5 on 2020-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0017_auto_20201013_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrquest',
            name='answer_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
