# Generated by Django 3.0.5 on 2020-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0018_auto_20201013_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrquest',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
