# Generated by Django 3.0.5 on 2020-10-13 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplesocial2', '0019_auto_20201013_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_group_name', models.CharField(max_length=255)),
                ('collaboration_group_members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
