# Generated by Django 3.0.5 on 2020-10-13 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplesocial2', '0020_collaborationgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationGroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=1024)),
                ('postpic', models.FileField(blank=True, null=True, upload_to='')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('collaboration_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.CollaborationGroup')),
                ('postlike', models.ManyToManyField(blank=True, related_name='group_postlikes', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NavBarDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NavBarDropdownCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.NavBarDropdown')),
            ],
        ),
        migrations.AddField(
            model_name='userpostcomment',
            name='commentlike',
            field=models.ManyToManyField(blank=True, related_name='user_commentlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='postlike',
            field=models.ManyToManyField(blank=True, related_name='user_postlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NavBarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=32)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplesocial2.NavBarDropdownCategory')),
                ('dropdown', models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplesocial2.NavBarDropdown')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationGroupPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1024)),
                ('commentpic', models.FileField(blank=True, null=True, upload_to='')),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
                ('collaboration_group_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.CollaborationGroupPost')),
                ('commentlike', models.ManyToManyField(blank=True, related_name='group_commentlikes', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
