# Generated by Django 3.0.5 on 2020-10-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0022_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplesocial2.NavBarDropdownCategory'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='dropdown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplesocial2.NavBarDropdown'),
        ),
    ]
