# Generated by Django 3.0.5 on 2020-10-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0024_auto_20201013_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='on_main_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='address',
            field=models.URLField(),
        ),
    ]
