# Generated by Django 3.0.5 on 2020-10-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0025_auto_20201013_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationgrouppost',
            name='postpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collaborationgrouppostcomment',
            name='commentpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitepost',
            name='postpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='postpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='commentpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
