# Generated by Django 3.0.5 on 2020-10-14 01:12

from django.db import migrations, models
import simplesocial2.models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0026_auto_20201013_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postpic',
            field=models.ImageField(blank=True, null=True, upload_to=simplesocial2.models.post_upload_dir),
        ),
    ]
