# Generated by Django 3.0.5 on 2020-10-15 00:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplesocial2', '0028_auto_20201014_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRquest',
            new_name='FriendRequest',
        ),
    ]
