# Generated by Django 3.0.5 on 2020-10-17 18:27

from django.db import migrations, models
import simplesocial2.models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0029_auto_20201015_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=simplesocial2.models.userprofile_avatar_upload_dir),
        ),
    ]
