# Generated by Django 3.0.5 on 2020-10-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0030_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.UserProfile'),
        ),
    ]
