# Generated by Django 3.0.5 on 2020-10-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplesocial2', '0031_auto_20201017_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationgrouppost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_username', to='simplesocial2.UserProfile'),
        ),
        migrations.AlterField(
            model_name='collaborationgrouppostcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.UserProfile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_by', to='simplesocial2.UserProfile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='simplesocial2.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplesocial2.UserProfile'),
        ),
    ]
